### ISSUE TITLE
1.20.1 Strange warns?

### ISSUE THREAD

**Issue by chmonyasik** [SrRapero720/dimthreads#18]
![Screenshot_6](https://github.com/SrRapero720/DimensionalThreading-Reforked/assets/94359925/cd411e10-6eeb-4b6b-a0bd-113b9b9d6060)

[latest.log](https://github.com/SrRapero720/DimensionalThreading-Reforked/files/15393425/latest.log)

Forge: 47.2.30
Minecraft: 1.20.1
Neruina, C2ME, dimthread-1.20.1-v1.0.0.jar, cupboard-1.20.1-2.6.jar, chunksending-1.20.1-2.8.jar (and a lot of other mods)

![image](https://github.com/SrRapero720/DimensionalThreading-Reforked/assets/94359925/719cfd23-aab4-4584-8cbc-4f32cbb81057)

Nothing seems to be lagging, and it hasn't gotten worse, but we need time for tests.

**Comment by SrRapero720** [comment]
Disable the warns on Cupboard config
cupboard concerns about entities spawned on threads that are not server threads (aka custom threads). but with dimensional threading ofc that was not possible.

Sadly cupboard make that spawn entity check inside a mixin so i can't force-disable it
i fixed on my side entities never got spanwed, so that warning is efectively useless

about your spark, ignore that, dimthreads consumes is on fire because it delegates all the tick job to other threads, making main thread just sit down and wait quietly until other threads finish.

for future reports (using spark) use `/spark profiler --thread *`, it will show all the worker threads of dimthread, so i can properly check what is happening
