### ISSUE TITLE
Invalid discord link

### ISSUE THREAD

**Issue by hckgg** [SrRapero720/dimthreads#2]
Discord link is invalid. Is it also possible to apply threads to certain dimensions? All the mods includes like 20 dimensions and I only want the overworld, nether, and end on separate threads as the other dimensions are not used enough.

**Comment by SrRapero720** [comment]
your request has no sense.
By default DimThreads asigns 3 threads to tick dimension in parallel, on normal minecraft, ticking dimensions are stacked onto how many dimensions exists on your world and tick chunks, entities, etc.

with 3 threads, you are saying to overworld, nether and end to tick at the same time in parallel and other dimensions needs to wait until any other dimension finishes to be ticked

---
imagine it like a waiting line, 3 people pass to the bathroom and other 17 needs to wait until someone leaves.
when someone leaves the next on the line pass to the bathroom. thats how it works.

disabling mod, only 1 dimension is tick-ed and others needs to wait for the current dimension.

if you give 20 threads, all dimensions got tick-ed at the same time, just ensure your CPU threads are enough to handle 20 threads, otherwise performance could be worse (depending of your hardware)

**Comment by SrRapero720** [comment]
i forgot to say, overworld, nether and end are the first dimension who got a tick. other dimensions are always behind.

**Comment by SrRapero720** [comment]
.
