### ISSUE TITLE
Full server crash 1.20.1

### ISSUE THREAD

**Issue by Bulwarini** [SrRapero720/dimthreads#21]
Server crushed, tick took too long
[crash-2024-06-24_08.46.14-server.txt](https://github.com/user-attachments/files/15956133/crash-2024-06-24_08.46.14-server.txt)

**Comment by SrRapero720** [comment]
I am aware
Dimthreads crashes are super cursed

Dimthreads deadlocks itself (apparently)
Also, you're using the 1.0.0

Update to the 1.0.4

**Comment by SrRapero720** [comment]
After properly reading the issue, overworld gets stuck loading a chunk...
try using `/gamerule dimthreads_active false`. if you experiment more watchdog crashes checkout what mod is causing it
Otherwise (if crashes aren't happening anymore) please open a issue, and the next time use any gist tool like from below

# 🖥️ PASTE PAGES
- **Github (100MB)**: https://gist.github.com/
- **MCLogs (10MB)**: https://mclo.gs/
- **PasteGG (15MB)**: https://paste.gg/
- **PasteEE (1MB)**: https://paste.ee/
- **HasteBin (400kB)**: https://hastebin.com/
- **CentOS (1MB)**: https://paste.centos.org/
